### ISSUE TITLE
Use AppCompatResources to properly support vector drawables

### ISSUE THREAD

**Issue by JasonHezz** [woxingxiao/VectorCompatTextView#1]
https://github.com/woxingxiao/VectorCompatTextView/blob/3c6149ce929b951055eeede4fae8b23d1a9eef04/vectorcompattextview/src/main/java/com/xw/repo/VectorCompatTextView.java#L64
```
dl = AppCompatResources.getDrawable(context, dlId)
```
**details**:
[Use AppCompatResources to properly support vector drawables](https://github.com/mikepenz/MaterialDrawer/pull/1731)

**Comment by woxingxiao** [comment]
我测试过，两种效果都一样。不过既然谷爹出了这个工具，总有他的道理，我已经在最新版2.0里使用了。

**Comment by JasonHezz** [comment]
Version under lolipop will crach,  have tested in Nexus_5X_API_18

**Comment by woxingxiao** [comment]
老铁，咱们还是中文交流吧，毕竟我英语不好。
我在4.1和4.4上均可以正常运行，能否贴下你的crash日志？

**Comment by JasonHezz** [comment]
ContextCompat.getDrawable(context,  dlId)在5.0以下获取VectorDrawable会crash,不过更新了2.0就不用纠结了,顺便把PR #2 merge下
