### ISSUE TITLE
无法导入项目

### ISSUE THREAD

**Issue by Jellyra** [woxingxiao/VectorCompatTextView#3]
gradle failed resolve: compile 'com.github.woxingxiao:VectorCompatTextView:2.2'

**Comment by woxingxiao** [comment]
是不是你的gradle处于offline work模式？

**Comment by woxingxiao** [comment]
@Jellyra 另外的注意点是，确保项目根目录的build.gradle中加入:
```groovy
  allprojects {
      repositories {
         maven { url "https://jitpack.io" } // 检查有没有这句话
      }
  }
```

**Comment by Jellyra** [comment]
@woxingxiao  成功，我放在了buildscript里去了，糊里糊涂的
